repos:
-   repo: local
    hooks:
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        stages: [commit]
-   repo: local
    hooks:
      - id: pycodestyle
        name: pycodestyle
        entry: pycodestyle
        language: system
        stages: [commit]
        types: [python]
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'python3 -m pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
# -   repo: local
#     hooks:
#     - id: pytest
#       name: pytest
#       language: system
#       entry: python3 -m pytest --cov=tests --cov-report html:cov_html
#       always_run: true
#       pass_filenames: false
#       stages: [commit]
